### ISSUE TITLE
Crash in beta branch 1.2.0

### ISSUE THREAD

**Issue by Immm3r** [Tyler-IN/MnB2-Bannerlord-CommunityPatch#180]
```
Recorded Unhandled Exceptions:
  1. System.NullReferenceException: Object reference not set to an instance of an object.
       at CommunityPatch.MenuCleaner.IsThirdPartyOption(InitialStateOption item)
       at CommunityPatch.MenuCleaner.CleanUpMainMenu()
       at CommunityPatch.CommunityPatchSubModule.OnBeforeInitialModuleScreenSetAsRoot()
       at TaleWorlds.MountAndBlade.Module.SetInitialModuleScreenAsRootScreen()
       at DMD<DMD<OnApplicationTick_Patch1>?52697953::OnApplicationTick_Patch1>(Module this, Single dt)
       at TaleWorlds.DotNet.Managed.ApplicationTick(Single dt)
       at DMD<DMD<Managed_ApplicationTick_Patch1>?36587673::Managed_ApplicationTick_Patch1>(Single dt)
```

The crash occures with BuyPatrols mod. If I disable either BuyPatrols or CommunityPatch game doesnt crash.

**Comment by Immm3r** [comment]
it happens only when CommunityPatch is before BuyPatrol in load order.
When you put CommunityPatch at the bottom in mod manager game doesnt crash.

Not sure if CommunityPatch should be at the bottom, may I experience some issues?

**Comment by KenRiehle** [comment]
![campaign crash](https://user-images.githubusercontent.com/24376503/79629383-5fd13b00-8117-11ea-96c4-e39071ae899e.JPG)


This is what I got when I tried to launch the game with Beta Branch 1.2.0

**Comment by Tyler-IN** [comment]
Should be fixed in the upcoming release.

**Comment by Tyler-IN** [comment]
Duplicates #169
