### ISSUE TITLE
AntiJank "issues"

### ISSUE THREAD

**Issue by Cebullus** [Tyler-IN/MnB2-Bannerlord-CommunityPatch#240]
Tested AntiJank from 0.1.0-rc2.

While this might be expected just wanted to share this nevertheless, using AntiJank breaks "Bannerlord Mod Launcher" with the following error/stacktrace:

System.Reflection.ReflectionTypeLoadException
  HResult=0x80131602
  Nachricht = Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
  Quelle = mscorlib
  Stapelüberwachung:
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.Assembly.GetTypes()
   at TaleWorlds.MountAndBlade.Module.CollectModuleAssemblyTypes(Assembly moduleAssembly)
   at TaleWorlds.MountAndBlade.Module.LoadSubModules()
   at TaleWorlds.MountAndBlade.Module.Initialize()

Native Launcher with AntiJank works fine ... problem is, that Bannerlord Mod Launcher is the only launcher at the moment which works perfectly with the mod "Party Screen Enhancements", especially the sorting functionality stops to work frequently.
The sorting functionality does not work consistently with the native launcher, native launcher+antijank, fixed Launcher. All with the same mod load order and PSE loaded last.

I have no clue what Bannerlord Mod Launcher does different than all the other ones.

**Comment by TYoung86** [comment]
Yeah - got a fix for it sent to a few testers, testing for next RC is ongoing.

**Comment by Tyler-IN** [comment]
Yeah - got a fix for it sent to a few testers, testing for next RC is ongoing.
