### ISSUE TITLE
Crash when obtaining fief on the random daily tick with CalculateProsperityChangeInternal_Patch2 method

### ISSUE THREAD

**Issue by Solganis** [Tyler-IN/MnB2-Bannerlord-CommunityPatch#295]
Can someone from a Dev team of the CommunityPatch confirm, that this crash have nothing to do with it? Pretty please, just in case. Because, I believe, that I don't have any other mod, that do something with this method.

Steps - 
1) Obtain a Castle/Town,
2) Start to upgrade it, (maybe irrelevant)
3) Just play the game normally,
4) It will crash on a random day tick.

1.4 Beta
CommunityPatch-rc5 (but it was happened before rc5, with rc2 too)

The crash is constant. You can't get pass it by disable some or all mods when you get it. Basically, you're save is doomed from that point.

```
Source: TaleWorlds.CampaignSystem 
Object reference not set to an instance of an object. 

at DMD?24490699::CalculateProsperityChangeInternal_Patch2>(DefaultSettlementProsperityModel this, Town fortification, StatExplainer explanation)
   at TaleWorlds.CampaignSystem.Town.DailyTick()
   at TaleWorlds.CampaignSystem.Campaign.DailyTickSettlement(Settlement settlement)
   at TaleWorlds.CampaignSystem.MbEvent`1.InvokeList(EventHandlerRec`1 list, T t)
   at TaleWorlds.CampaignSystem.CampaignEvents.DailyTickSettlement(Settlement settlement)
   at TaleWorlds.CampaignSystem.CampaignEventDispatcher.DailyTickSettlement(Settlement settlement)
   at TaleWorlds.CampaignSystem.PeriodicTicker`1.PeriodicTickSome(Single timeUnitsElaped)
   at TaleWorlds.CampaignSystem.Campaign.Tick(Single dt)
   at TaleWorlds.CampaignSystem.Campaign.RealTick(Single realDt)
   at TaleWorlds.CampaignSystem.MapState.OnMapModeTick(Single dt)
   at TaleWorlds.Core.GameStateManager.OnTick(Single dt)
   at TaleWorlds.Core.Game.OnTick(Single dt)
   at TaleWorlds.Core.GameManagerBase.OnTick(Single dt)
   at DMD?66083951::OnApplicationTick_Patch1>(Module this, Single dt)
```

After disabling CommunityPatch, crash log are a little different for some reason - 

```
Source: TaleWorlds.CampaignSystem 
Object reference not set to an instance of an object. 

 at TaleWorlds.CampaignSystem.SandBox.GameComponents.DefaultSettlementProsperityModel.CalculateProsperityChangeInternal(Town fortification, StatExplainer explanation)
   at TaleWorlds.CampaignSystem.Town.DailyTick()
   at TaleWorlds.CampaignSystem.Campaign.DailyTickSettlement(Settlement settlement)
   at TaleWorlds.CampaignSystem.MbEvent`1.InvokeList(EventHandlerRec`1 list, T t)
   at TaleWorlds.CampaignSystem.CampaignEvents.DailyTickSettlement(Settlement settlement)
   at TaleWorlds.CampaignSystem.CampaignEventDispatcher.DailyTickSettlement(Settlement settlement)
   at TaleWorlds.CampaignSystem.PeriodicTicker`1.PeriodicTickSome(Single timeUnitsElaped)
   at TaleWorlds.CampaignSystem.Campaign.Tick(Single dt)
   at TaleWorlds.CampaignSystem.Campaign.RealTick(Single realDt)
   at TaleWorlds.CampaignSystem.MapState.OnMapModeTick(Single dt)
   at TaleWorlds.Core.GameStateManager.OnTick(Single dt)
   at TaleWorlds.Core.Game.OnTick(Single dt)
   at TaleWorlds.Core.GameManagerBase.OnTick(Single dt)
   at DMD?66083951::OnApplicationTick_Patch1>(Module this, Single dt)
```

**Comment by Tyler-IN** [comment]
Need a save that's trimmed down on mods to quickly reproduce for debugging.

**Comment by Tyler-IN** [comment]
Reopening for discussion

**Comment by Tyler-IN** [comment]
Bug in game; somehow possible for a Town to not have a CurrentBuilding (by way of not having a CurrentDefaultBuilding).

Added a fallback to CurrentDefaultBuilding that will just pick a random daily default if it would otherwise be null.

Should be solved.

**Comment by Solganis** [comment]
This patch solves my problem with this save. (and perhaps, many others, that was doomed with this crash)

Once again, thanks to magician @Tyler-IN fordebugging and overall much appreciated help in a time of need. I hope, this fix gonna save someone much need nerve cells and most importantly - TIME.

Closing it for now.
