### ISSUE TITLE
Several patches don't apply

### ISSUE THREAD

**Issue by Jayell123** [Tyler-IN/MnB2-Bannerlord-CommunityPatch#345]
```
:0:0: ArgumentNullException: Value cannot be null.
Parameter name: key 
   at System.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Collections.Generic.Dictionary`2.FindEntry(TKey key)
   at System.Collections.Generic.Dictionary`2.TryGetValue(TKey key, TValue& value)
   at HarmonyLib.GeneralExtensions.GetValueSafe[S,T](Dictionary`2 dictionary, S key)
   at HarmonyLib.HarmonySharedState.GetPatchInfo(MethodBase method)
   at HarmonyLib.PatchProcessor.GetPatchInfo(MethodBase method)
   at CommunityPatch.PatchApplicabilityHelper.IsTargetPatchable(MethodInfo targetMethodInfo, Byte[][] targetHashes)
   at CommunityPatch.Patches.Perks.Social.Leadership.UltimateLeaderPatch.IsApplicable(Game game)
   at CommunityPatch.CommunityPatchSubModule.ApplyPatches(Game game) 

:0:0: MissingMethodException: Method not found: 'Void TaleWorlds.CampaignSystem.PerkObject.Initialize(System.String, System.String, TaleWorlds.Core.SkillObject, Int32, TaleWorlds.CampaignSystem.PerkObject, PerkRole, Single, PerkRole, Single, EffectIncrementType)'. 
   at CommunityPatch.PerkObjectExtensions.Modify(PerkObject perk, PerkRole primaryRole, Single primaryBonus, EffectIncrementType incrementType)
   at CommunityPatch.Patches.Perks.Endurance.Riding.NomadicTraditionsPerkObjectPatch.Apply(Game game)
   at CommunityPatch.CommunityPatchSubModule.ApplyPatches(Game game) 

:0:0: MissingMethodException: Method not found: 'Void TaleWorlds.CampaignSystem.PerkObject.Initialize(System.String, System.String, TaleWorlds.Core.SkillObject, Int32, TaleWorlds.CampaignSystem.PerkObject, PerkRole, Single, PerkRole, Single, EffectIncrementType)'. 
   at CommunityPatch.PerkObjectExtensions.Modify(PerkObject perk, PerkRole primaryRole, Single primaryBonus, EffectIncrementType incrementType)
   at CommunityPatch.Patches.Perks.Intelligence.Steward.AgrarianPatch.Apply(Game game)
   at CommunityPatch.CommunityPatchSubModule.ApplyPatches(Game game) 

:0:0: MissingMethodException: Method not found: 'Void TaleWorlds.CampaignSystem.PerkObject.Initialize(System.String, System.String, TaleWorlds.Core.SkillObject, Int32, TaleWorlds.CampaignSystem.PerkObject, PerkRole, Single, PerkRole, Single, EffectIncrementType)'. 
   at CommunityPatch.PerkObjectExtensions.Modify(PerkObject perk, PerkRole primaryRole, Single primaryBonus, EffectIncrementType incrementType)
   at CommunityPatch.Patches.Perks.Intelligence.Steward.AssessorPatch.Apply(Game game)
   at CommunityPatch.CommunityPatchSubModule.ApplyPatches(Game game) 

:0:0: MissingMethodException: Method not found: 'Void TaleWorlds.CampaignSystem.PerkObject.Initialize(System.String, System.String, TaleWorlds.Core.SkillObject, Int32, TaleWorlds.CampaignSystem.PerkObject, PerkRole, Single, PerkRole, Single, EffectIncrementType)'. 
   at CommunityPatch.PerkObjectExtensions.Modify(PerkObject perk, PerkRole primaryRole, Single primaryBonus, EffectIncrementType incrementType)
   at CommunityPatch.Patches.Perks.Intelligence.Steward.EnhancedMinesPatch.Apply(Game game)
   at CommunityPatch.CommunityPatchSubModule.ApplyPatches(Game game) 

:0:0: MissingMethodException: Method not found: 'Void TaleWorlds.CampaignSystem.PerkObject.Initialize(System.String, System.String, TaleWorlds.Core.SkillObject, Int32, TaleWorlds.CampaignSystem.PerkObject, PerkRole, Single, PerkRole, Single, EffectIncrementType)'. 
   at CommunityPatch.PerkObjectExtensions.Modify(PerkObject perk, PerkRole primaryRole, Single primaryBonus, EffectIncrementType incrementType)
   at CommunityPatch.Patches.Perks.Intelligence.Steward.ReconstructionPatch.Apply(Game game)
   at CommunityPatch.CommunityPatchSubModule.ApplyPatches(Game game) 

:0:0: MissingMethodException: Method not found: 'Void TaleWorlds.CampaignSystem.PerkObject.Initialize(System.String, System.String, TaleWorlds.Core.SkillObject, Int32, TaleWorlds.CampaignSystem.PerkObject, PerkRole, Single, PerkRole, Single, EffectIncrementType)'. 
   at CommunityPatch.PerkObjectExtensions.Modify(PerkObject perk, PerkRole primaryRole, Single primaryBonus, EffectIncrementType incrementType)
   at CommunityPatch.Patches.Perks.Intelligence.Engineering.BuilderPatch.Apply(Game game)
   at CommunityPatch.CommunityPatchSubModule.ApplyPatches(Game game) 

:0:0: MissingMethodException: Method not found: 'Void TaleWorlds.CampaignSystem.PerkObject.Initialize(System.String, System.String, TaleWorlds.Core.SkillObject, Int32, TaleWorlds.CampaignSystem.PerkObject, PerkRole, Single, PerkRole, Single, EffectIncrementType)'. 
   at CommunityPatch.PerkObjectExtensions.Modify(PerkObject perk, PerkRole primaryRole, Single primaryBonus, EffectIncrementType incrementType)
   at CommunityPatch.Patches.Perks.Intelligence.Engineering.EverydayEngineerPatch.Apply(Game game)
   at CommunityPatch.CommunityPatchSubModule.ApplyPatches(Game game) 

:0:0: MissingMethodException: Method not found: 'Void TaleWorlds.CampaignSystem.PerkObject.Initialize(System.String, System.String, TaleWorlds.Core.SkillObject, Int32, TaleWorlds.CampaignSystem.PerkObject, PerkRole, Single, PerkRole, Single, EffectIncrementType)'. 
   at CommunityPatch.PerkObjectExtensions.Modify(PerkObject perk, PerkRole primaryRole, Single primaryBonus, EffectIncrementType incrementType)
   at CommunityPatch.Patches.Perks.Intelligence.Engineering.ImperialFirePatch.Apply(Game game)
   at CommunityPatch.CommunityPatchSubModule.ApplyPatches(Game game) 

:0:0: MissingMethodException: Method not found: 'Void TaleWorlds.CampaignSystem.PerkObject.Initialize(System.String, System.String, TaleWorlds.Core.SkillObject, Int32, TaleWorlds.CampaignSystem.PerkObject, PerkRole, Single, PerkRole, Single, EffectIncrementType)'. 
   at CommunityPatch.PerkObjectExtensions.Modify(PerkObject perk, PerkRole primaryRole, Single primaryBonus, EffectIncrementType incrementType)
   at CommunityPatch.Patches.Perks.Intelligence.Engineering.ImprovedMasonryPatch.Apply(Game game)
   at CommunityPatch.CommunityPatchSubModule.ApplyPatches(Game game) 

:0:0: MissingMethodException: Method not found: 'Void TaleWorlds.CampaignSystem.PerkObject.Initialize(System.String, System.String, TaleWorlds.Core.SkillObject, Int32, TaleWorlds.CampaignSystem.PerkObject, PerkRole, Single, PerkRole, Single, EffectIncrementType)'. 
   at CommunityPatch.PerkObjectExtensions.Modify(PerkObject perk, PerkRole primaryRole, Single primaryBonus, EffectIncrementType incrementType)
   at CommunityPatch.Patches.Perks.Intelligence.Engineering.ResolutePatch.Apply(Game game)
   at CommunityPatch.CommunityPatchSubModule.ApplyPatches(Game game) 

:0:0: MissingMethodException: Method not found: 'Void TaleWorlds.CampaignSystem.PerkObject.Initialize(System.String, System.String, TaleWorlds.Core.SkillObject, Int32, TaleWorlds.CampaignSystem.PerkObject, PerkRole, Single, PerkRole, Single, EffectIncrementType)'. 
   at CommunityPatch.Patches.Perks.Cunning.Tactics.TrustedCommandersPatch.Apply(Game game)
   at CommunityPatch.CommunityPatchSubModule.ApplyPatches(Game game) 

:0:0: MissingMethodException: Method not found: 'Void TaleWorlds.CampaignSystem.PerkObject.Initialize(System.String, System.String, TaleWorlds.Core.SkillObject, Int32, TaleWorlds.CampaignSystem.PerkObject, PerkRole, Single, PerkRole, Single, EffectIncrementType)'. 
   at CommunityPatch.PerkObjectExtensions.Modify(PerkObject perk, PerkRole primaryRole, Single primaryBonus, EffectIncrementType incrementType)
   at CommunityPatch.Patches.Perks.Cunning.Roguery.BriberPatch.Apply(Game game)
   at CommunityPatch.CommunityPatchSubModule.ApplyPatches(Game game) 

:0:0: MissingMethodException: Method not found: 'Void TaleWorlds.CampaignSystem.PerkObject.Initialize(System.String, System.String, TaleWorlds.Core.SkillObject, Int32, TaleWorlds.CampaignSystem.PerkObject, PerkRole, Single, PerkRole, Single, EffectIncrementType)'. 
   at CommunityPatch.PerkObjectExtensions.Modify(PerkObject perk, PerkRole primaryRole, Single primaryBonus, EffectIncrementType incrementType)
   at CommunityPatch.Patches.Perks.Cunning.Roguery.EscapeArtistPatch.Apply(Game game)
   at CommunityPatch.CommunityPatchSubModule.ApplyPatches(Game game) 

:0:0: MissingMethodException: Method not found: 'Void TaleWorlds.CampaignSystem.PerkObject.Initialize(System.String, System.String, TaleWorlds.Core.SkillObject, Int32, TaleWorlds.CampaignSystem.PerkObject, PerkRole, Single, PerkRole, Single, EffectIncrementType)'. 
   at CommunityPatch.PerkObjectExtensions.Modify(PerkObject perk, PerkRole primaryRole, Single primaryBonus, EffectIncrementType incrementType)
   at CommunityPatch.Patches.Perks.Cunning.Roguery.ForTheThrillPatch.Apply(Game game)
   at CommunityPatch.CommunityPatchSubModule.ApplyPatches(Game game)
```

**Comment by Tyler-IN** [comment]
That is a subset of patches that don't apply, sure, but not "nothing works" level.

Would you mind providing relevant details, like what version of the game and what version of the mod?

**Comment by Tyler-IN** [comment]
Nomadic Traditions,
Agrarian,
Assessor,
Enhanced Mines,
Reconstruction,
Builder (1, looks like 2 must have applied),
Everyday Engineer,
Imperial Fire,
Improved Masonry,
Resolute,
Trusted Commanders,
Briber,
Escape Artist,
For The Thrill

Since Builder 2 applied I assume you're on v1.4.1?

**Comment by Tyler-IN** [comment]
This is too broad to classify as a bug.

Possibly related to https://github.com/Tyler-IN/MnB2-Bannerlord-CommunityPatch/issues/338

**Comment by Jayell123** [comment]
I am indeed on 1.4.1! I don't think this is a community patch issue after all. Thanks for the reply! I am going to uninstall all mods and start fresh with just community patch and Bannerlord tweaks.
