### ISSUE TITLE
I tried the updated version for 1.4.1 and the 1.4.0 but I run into the same error

### ISSUE THREAD

**Issue by Jayell123** [Tyler-IN/MnB2-Bannerlord-CommunityPatch#346]
Here is the debug log. My current savegame has nearly 70 hours on it so I really hope you guys are able to find a fix! Thanks!

- Reasons
Source: mscorlib
Exception has been thrown by the target of an invocation.

- Inner exception
Source: TaleWorlds.CampaignSystem.ViewModelCollection
Object reference not set to an instance of an object.

- Callstacks
Protip: Use a debugger like dnSpy or Visual studio to trace the source of error, by stepping the program line by line.

Inner exception callstack:
   at TaleWorlds.CampaignSystem.ViewModelCollection.GameMenu.RecruitVolunteerTroopVM..ctor(RecruitVolunteerVM owner, CharacterObject character, Int32 index, Action`1 onClick, Action`1 onRemoveFromCart)
   at TaleWorlds.CampaignSystem.ViewModelCollection.GameMenu.RecruitVolunteerVM..ctor(Hero owner, List`1 troops, Action`2 onRecruit, Action`2 onRemoveFromCart)
   at TaleWorlds.CampaignSystem.ViewModelCollection.GameMenu.RecruitmentVM.RefreshScreen()
   at TaleWorlds.CampaignSystem.ViewModelCollection.GameMenu.RecruitmentVM.RefreshValues()
   at TaleWorlds.CampaignSystem.ViewModelCollection.GameMenu.RecruitmentVM..ctor()
   at SandBox.GauntletUI.GauntletMenuRecruitVolunteers.OnInitialize()
   at SandBox.View.Menu.MenuViewContext.AddMenuView[T](Object[] parameters)
   at SandBox.View.Menu.MenuViewContext.TaleWorlds.CampaignSystem.IMenuContextHandler.OnOpenRecruitVolunteers()
   at TaleWorlds.CampaignSystem.GameMenus.GameMenuInitializationHandlers.PlayerTownVisit.game_menu_recruit_volunteers_on_consequence(MenuCallbackArgs args)
   at TaleWorlds.CampaignSystem.GameMenus.GameMenuCallbackManager.OnConsequence(String menuId, GameMenuOption gameMenuOption, MenuContext state)
   at TaleWorlds.CampaignSystem.GameMenus.GameMenuOption.RunConsequence(MenuContext menuContext)
Outer exception callstack:
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at TaleWorlds.Library.Common.InvokeWithLog(MethodInfo methodInfo, Object obj, Object[] args)
   at DMD?12208833::ExecuteCommand_Patch1>(ViewModel this, String commandName, Object[] parameters)
   at TaleWorlds.GauntletUI.Data.GauntletView.OnCommand(String command, Object[] args)
   at System.Action`3.Invoke(T1 arg1, T2 arg2, T3 arg3)
   at TaleWorlds.GauntletUI.Widget.EventFired(String eventName, Object[] args)
   at TaleWorlds.GauntletUI.ButtonWidget.HandleClick()
   at TaleWorlds.GauntletUI.ButtonWidget.OnMouseReleased()
   at TaleWorlds.GauntletUI.EventManager.MouseUp()
   at TaleWorlds.GauntletUI.UIContext.UpdateInput(InputType handleInputs)
   at TaleWorlds.Engine.Screens.ScreenManager.Update()
   at DMD?11171691::Tick_Patch1>(Single dt)

**Comment by Tyler-IN** [comment]
This doesn't appear to be related to Community Patch.

Does this happen without Community Patch loaded?

**Comment by Jayell123** [comment]
Yeah :| I dunno wat to do. Every city isn't buying food from their villagers and caravans too now. I think I just need to uninstall all of my mods and start fresh. Pretty sad tbh but maybe I can salvage my save game.

**Comment by Blankfive** [comment]
I get this error aswell when trying to recruit troops in a village. I also get this error when I try to attack certain armies, which may be related:

https://imgur.com/BMnBbgr

Both of these errors occur even after completely reinstalling the game and starting new saves.
