### ISSUE TITLE
New hotfix breaks community patch

### ISSUE THREAD

**Issue by Ski-Mississippi** [Tyler-IN/MnB2-Bannerlord-CommunityPatch#362]
Source: CommunityPatch
Method not found: 'Void TaleWorlds.CampaignSystem.ExplainedNumber.Add(Single, TaleWorlds.Localization.TextObject)'.

Inner exception callstack:
No inner exception was thrown
Outer exception callstack:
   at CommunityPatch.Patches.Feats.BattanianForestAgilityPatch.Postfix(DefaultPartySpeedCalculatingModel __instance, MobileParty& mobileParty, Single& baseSpeed, StatExplainer& explanation, Single& __result)
   at DMD?2973742::CalculateFinalSpeed_Patch3>(DefaultPartySpeedCalculatingModel this, MobileParty mobileParty, Single baseSpeed, StatExplainer explanation)
   at TaleWorlds.CampaignSystem.MobileParty.ComputeSpeed()
   at TaleWorlds.CampaignSystem.ViewModelCollection.Map.MapInfoVM.UpdatePlayerInfo()
   at TaleWorlds.CampaignSystem.ViewModelCollection.MapVM.OnRefresh()
   at TaleWorlds.CampaignSystem.ViewModelCollection.MapVM..ctor(INavigationHandler navigationHandler, IMapStateHandler mapStateHandler, MapBarShortcuts shortcuts, Action openArmyManagement)
   at SandBox.GauntletUI.Map.GauntlerMapBarGlobalLayer.Initialize(MapScreen mapScreen)
   at SandBox.GauntletUI.Map.GauntletMapBar.CreateLayout()
   at SandBox.View.Map.MapScreen.AddMapView[T](Object[] parameters)
   at SandBox.View.Map.MapScreen.OnInitialize()
   at TaleWorlds.Engine.Screens.ScreenBase.HandleInitialize()
   at TaleWorlds.Engine.Screens.ScreenManager.CleanAndPushScreen(ScreenBase screen)
   at TaleWorlds.Core.GameStateManager.OnPushState(GameState gameState)
   at TaleWorlds.Core.GameStateManager.OnCleanAndPushState(GameState gameState)
   at TaleWorlds.Core.GameStateManager.DoGameStateJobs()
   at TaleWorlds.Core.GameStateManager.CleanAndPushState(GameState gameState, Int32 level)
   at SandBox.CampaignGameManager.OnLoadFinished()
   at TaleWorlds.Core.GameStateManager.OnTick(Single dt)
   at DMD?61844338::OnApplicationTick_Patch1>(Module this, Single dt)

**Comment by azirok** [comment]
same

**Comment by xiaofeinot** [comment]
SAME

**Comment by joshualawhead** [comment]
Same

**Comment by 13ootyknight** [comment]
Same

**Comment by walterchin** [comment]
Same

**Comment by Solganis** [comment]
sAme

**Comment by Swordofheaven** [comment]
same

**Comment by exoticdisease** [comment]
Same

**Comment by divyanthj** [comment]
Same here. Took some 2 hours to figure this out!! Kindly fix! The game is useless without this patch.

**Comment by EPCarter** [comment]
Same

**Comment by Figulus** [comment]
Please fix... lovely community patch people.

**Comment by koyteck** [comment]
Sadly, I have the same issue

**Comment by Jayell123** [comment]
Same

**Comment by timchu90** [comment]
doesn't seem like the patch leadership is too active anymore. I will say that one of the devs here has a working fix waiting in the pull requests here: https://github.com/JoeFwd/MnB2-Bannerlord-CommunityPatch/tree/bump-fixes-after-new-1.4.1-hotfix 

tested it out myself, and while i cant verify every perk is fixed, at least it runs!

**Comment by Solganis** [comment]
@timchu90 can you post a build with this pull request here?

**Comment by timchu90** [comment]
sure, i dont see why not. 
https://drive.google.com/file/d/1DtngTA8ypDt7M7kOzNNTA3n8CqUlP2-J/view?usp=sharing

**Comment by Ski-Mississippi** [comment]
dumb questions... The gdrive link above has the updated CommunityPatch that is at least playable?

**Comment by timchu90** [comment]
> dumb questions... The gdrive link above has the updated CommunityPatch that is at least playable?

Yes. I havent encountered any crashes yet. But like I said, this is an interim build that hasn't been verified by other devs. I'm just too impatient to wait for an official release. No guarantee that it will work perfectly.

**Comment by Ski-Mississippi** [comment]
Sweet action! I'm not too worried about everything working as long as I can get my save to run. Thanks @timchu90

**Comment by timchu90** [comment]
all credit goes to @JoeFwd
