### ISSUE TITLE
Crash on community options, character creation and save load

### ISSUE THREAD

**Issue by bomb77** [Tyler-IN/MnB2-Bannerlord-CommunityPatch#375]
Hi,
I'm getting these crashes with 1.41 and 1.4 (im on 1.41). 
Any help would be much appreciated

Source: CommunityPatch 
Method not found: 'Void TaleWorlds.CampaignSystem.ExplainedNumber.Add(Single, TaleWorlds.Localization.TextObject)'. 

- Inner exception
Source: No module 
No inner exception was thrown 

- Callstacks
Protip: Use a debugger like dnSpy or Visual studio to trace the source of error, by stepping the program line by line. 

Inner exception callstack: 
No inner exception was thrown
Outer exception callstack: 
   at CommunityPatch.Patches.Feats.BattanianForestAgilityPatch.Postfix(DefaultPartySpeedCalculatingModel __instance, MobileParty& mobileParty, Single& baseSpeed, StatExplainer& explanation, Single& __result)
   at DMD?51262028::CalculateFinalSpeed_Patch3>(DefaultPartySpeedCalculatingModel this, MobileParty mobileParty, Single baseSpeed, StatExplainer explanation)
   at TaleWorlds.CampaignSystem.MobileParty.ComputeSpeed()
   at TaleWorlds.CampaignSystem.ViewModelCollection.Map.MapInfoVM.UpdatePlayerInfo()
   at TaleWorlds.CampaignSystem.ViewModelCollection.MapVM.OnRefresh()
   at TaleWorlds.CampaignSystem.ViewModelCollection.MapVM..ctor(INavigationHandler navigationHandler, IMapStateHandler mapStateHandler, MapBarShortcuts shortcuts, Action openArmyManagement)
   at SandBox.GauntletUI.Map.GauntlerMapBarGlobalLayer.Initialize(MapScreen mapScreen)
   at SandBox.GauntletUI.Map.GauntletMapBar.CreateLayout()
   at SandBox.View.Map.MapScreen.AddMapView[T](Object[] parameters)
   at SandBox.View.Map.MapScreen.OnInitialize()
   at TaleWorlds.Engine.Screens.ScreenBase.HandleInitialize()
   at TaleWorlds.Engine.Screens.ScreenManager.CleanAndPushScreen(ScreenBase screen)
   at TaleWorlds.Core.GameStateManager.OnPushState(GameState gameState)
   at TaleWorlds.Core.GameStateManager.OnCleanAndPushState(GameState gameState)
   at TaleWorlds.Core.GameStateManager.DoGameStateJobs()
   at TaleWorlds.Core.GameStateManager.CleanAndPushState(GameState gameState, Int32 level)
   at SandBox.CampaignGameManager.OnLoadFinished()
   at TaleWorlds.Core.GameStateManager.OnTick(Single dt)
   at DMD?28903261::OnApplicationTick_Patch2>(Module this, Single dt)

**Comment by bomb77** [comment]
Nevermind, I used this version of the patch (as opposed to the nexus version) and it's all good https://github.com/Tyler-IN/MnB2-Bannerlord-CommunityPatch/releases/download/v0.1.0-rc7/CommunityPatch-e1.4.1.zip
