### ISSUE TITLE
Crash on 1.5.0 Beta

### ISSUE THREAD

**Issue by v3ntril0quist** [Tyler-IN/MnB2-Bannerlord-CommunityPatch#406]
No sign of error starting the game, start a new campaign and when start moving on campaign map I got the crash error message:

---------------------------
Mount and Blade Bannerlord has crashed
---------------------------
Mount and Blade Bannerlord has encountered an error and needs to close. See the error information below.

MissingMethodException:

Method not found: 'Void Helpers.PerkHelper.AddPerkBonusForParty(TaleWorlds.CampaignSystem.PerkObject, TaleWorlds.CampaignSystem.MobileParty, TaleWorlds.CampaignSystem.ExplainedNumber ByRef)'.

Stack trace:

   at CommunityPatch.Patches.Perks.Cunning.Tactics.TrustedCommandersPatch.PartyHasPerk(MobileParty party, PerkObject perk)

   at CommunityPatch.Patches.Perks.Cunning.Tactics.TrustedCommandersPatch.CalculatePerkReduction(Army army, PerkObject perk) in C:\Program Files (x86)\Steam\steamapps\common\Mount & Blade II Bannerlord\Modules\CommunityPatch\src\CommunityPatch\Patches\Perks\Cunning\Tactics\TrustedCommandersPatch.cs:line 102

   at CommunityPatch.Patches.Perks.Cunning.Tactics.TrustedCommandersPatch.Postfix(Single& __result, Army army, StatExplainer explanation) in C:\Program Files (x86)\Steam\steamapps\common\Mount & Blade II Bannerlord\Modules\CommunityPatch\src\CommunityPatch\Patches\Perks\Cunning\Tactics\TrustedCommandersPatch.cs:line 92

   at TaleWorlds.CampaignSystem.SandBox.GameComponents.Map.DefaultArmyManagementCalculationModel.CalculateCohesionChange_Patch1(DefaultArmyManagementCalculationModel this, Army army, StatExplainer explanation)

   at TaleWorlds.CampaignSystem.Army.HourlyTick(MBCampaignEvent campaignevent, Object[] delegateparams)

   at TaleWorlds.CampaignSystem.MBCampaignEvent.RunHandlers(Object[] delegateParams)

   at TaleWorlds.CampaignSystem.MBCampaignEvent.CheckUpdate()

   at TaleWorlds.CampaignSystem.CampaignEvents.SignalPeriodicEvents()

   at TaleWorlds.CampaignSystem.Campaign.Tick(Single dt)

   at TaleWorlds.CampaignSystem.Campaign.RealTick(Single realDt)

   at TaleWorlds.CampaignSystem.MapState.OnMapModeTick(Single dt)

   at TaleWorlds.Core.GameStateManager.OnTick(Single dt)

   at TaleWorlds.Core.Game.OnTick(Single dt)

   at TaleWorlds.Core.GameManagerBase.OnTick(Single dt)

   at TaleWorlds.MountAndBlade.Module.OnApplicationTick_Patch1(Module this, Single dt)

---------------------------
Mount and Blade Bannerlord has crashed
---------------------------
Mount and Blade Bannerlord has encountered an error and needs to close. See the error information below.

MissingMethodException:

Method not found: 'Void Helpers.PerkHelper.AddPerkBonusForParty(TaleWorlds.CampaignSystem.PerkObject, TaleWorlds.CampaignSystem.MobileParty, TaleWorlds.CampaignSystem.ExplainedNumber ByRef)'.

Stack trace:

   at CommunityPatch.Patches.Perks.Cunning.Tactics.TrustedCommandersPatch.PartyHasPerk(MobileParty party, PerkObject perk)

   at CommunityPatch.Patches.Perks.Cunning.Tactics.TrustedCommandersPatch.CalculatePerkReduction(Army army, PerkObject perk) in C:\Program Files (x86)\Steam\steamapps\common\Mount & Blade II Bannerlord\Modules\CommunityPatch\src\CommunityPatch\Patches\Perks\Cunning\Tactics\TrustedCommandersPatch.cs:line 102

   at CommunityPatch.Patches.Perks.Cunning.Tactics.TrustedCommandersPatch.Postfix(Single& __result, Army army, StatExplainer explanation) in C:\Program Files (x86)\Steam\steamapps\common\Mount & Blade II Bannerlord\Modules\CommunityPatch\src\CommunityPatch\Patches\Perks\Cunning\Tactics\TrustedCommandersPatch.cs:line 92

   at TaleWorlds.CampaignSystem.SandBox.GameComponents.Map.DefaultArmyManagementCalculationModel.CalculateCohesionChange_Patch1(DefaultArmyManagementCalculationModel this, Army army, StatExplainer explanation)

   at TaleWorlds.CampaignSystem.Army.HourlyTick(MBCampaignEvent campaignevent, Object[] delegateparams)

   at TaleWorlds.CampaignSystem.MBCampaignEvent.RunHandlers(Object[] delegateParams)

   at TaleWorlds.CampaignSystem.MBCampaignEvent.CheckUpdate()

   at TaleWorlds.CampaignSystem.CampaignEvents.SignalPeriodicEvents()

   at TaleWorlds.CampaignSystem.Campaign.Tick(Single dt)

   at TaleWorlds.CampaignSystem.Campaign.RealTick(Single realDt)

   at TaleWorlds.CampaignSystem.MapState.OnMapModeTick(Single dt)

   at TaleWorlds.Core.GameStateManager.OnTick(Single dt)

   at TaleWorlds.Core.Game.OnTick(Single dt)

   at TaleWorlds.Core.GameManagerBase.OnTick(Single dt)

   at TaleWorlds.MountAndBlade.Module.OnApplicationTick_Patch1(Module this, Single dt)

   at TaleWorlds.DotNet.Managed.ApplicationTick_Patch1(Single dt)

**Comment by JoeFwd** [comment]
Community Patch is not compatible with beta e1.5.0.

**Comment by v3ntril0quist** [comment]
Understandable, just posting in case it would be helpful for future release.

**Comment by MiStavoL** [comment]
[url=https://hizliresim.com/9cJwCV][img]https://i.hizliresim.com/9cJwCV.png[/img][/url]
[url=https://hizliresim.com/gPLoFx][img]https://i.hizliresim.com/gPLoFx.png[/img][/url]
