### ISSUE TITLE
StewardSwordsAsTributePatch causing crash to desktop on Kingdom Leave

### ISSUE THREAD

**Issue by tynakuh** [Tyler-IN/MnB2-Bannerlord-CommunityPatch#73]
Upon an attempt to leave Kingdom crashing to desktop

Stacktrace:

```Recorded Unhandled Exceptions:
  1. System.InvalidOperationException: Operation is not valid due to the current state of the object.
       at System.Reflection.MemberInfo.get_MetadataToken()
       at TaleWorlds.Library.Common.GetStackTraceRaw(Exception e, Int32 skipCount)
       at TaleWorlds.Library.Common.WalkInnerExceptionRecursive(Exception InnerException, String& StackStr)
       at TaleWorlds.Library.Common.WalkInnerExceptionRecursive(Exception InnerException, String& StackStr)
       at TaleWorlds.Library.Common.PrintDynamicInvokeDebugInfo(Exception e, MethodInfo methodInfo, Object obj, Object[] args)
       at TaleWorlds.Library.Common.InvokeWithLog(MethodInfo methodInfo, Object obj, Object[] args)
       at TaleWorlds.Library.ViewModel.ExecuteCommand(String commandName, Object[] parameters)
       at TaleWorlds.GauntletUI.Data.GauntletView.OnCommand(String command, Object[] args)
       at TaleWorlds.GauntletUI.Data.GauntletView.OnEventFired(Widget widget, String commandName, Object[] args)
       at TaleWorlds.GauntletUI.Widget.EventFired(String eventName, Object[] args)
       at TaleWorlds.GauntletUI.ButtonWidget.HandleClick()
       at TaleWorlds.GauntletUI.ButtonWidget.OnMouseReleased()
       at TaleWorlds.GauntletUI.EventManager.DispatchEvent(Widget selectedWidget, GauntletEvent gauntletEvent)
       at TaleWorlds.GauntletUI.EventManager.MouseUp()
       at TaleWorlds.GauntletUI.UIContext.UpdateInput(InputType handleInputs)
       at TaleWorlds.Engine.GauntletUI.GauntletLayer.ProcessEvents()
       at TaleWorlds.Engine.Screens.ScreenManager.Update()
       at TaleWorlds.Engine.Screens.ScreenManager.Tick(Single dt)
       at ManagedCallbacks.EngineCallbacksGenerated.ScreenManager_Tick(Single dt)

Recorded First Chance Exceptions:
  1. System.ArgumentException: Illegal characters in path.
       at System.IO.LongPathHelper.Normalize(String path, UInt32 maxPathLength, Boolean checkInvalidCharacters, Boolean expandShortPaths)
       at System.IO.Path.NewNormalizePath(String path, Int32 maxPathLength, Boolean expandShortPaths)
       at System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
       at System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength)
       at System.IO.Path.NormalizePath(String path, Boolean fullCheck)
       at System.IO.Path.GetFullPathInternal(String path)
       at System.Reflection.RuntimeModule.get_FullyQualifiedName()
  2. System.ArgumentException: Illegal characters in path.
       at System.IO.LongPathHelper.Normalize(String path, UInt32 maxPathLength, Boolean checkInvalidCharacters, Boolean expandShortPaths)
       at System.IO.Path.NewNormalizePath(String path, Int32 maxPathLength, Boolean expandShortPaths)
       at System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
       at System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength)
       at System.IO.Path.NormalizePath(String path, Boolean fullCheck)
       at System.IO.Path.GetFullPathInternal(String path)
       at System.Reflection.RuntimeModule.get_FullyQualifiedName()
  3. System.ArgumentException: Illegal characters in path.
       at System.IO.LongPathHelper.Normalize(String path, UInt32 maxPathLength, Boolean checkInvalidCharacters, Boolean expandShortPaths)
       at System.IO.Path.NewNormalizePath(String path, Int32 maxPathLength, Boolean expandShortPaths)
       at System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
       at System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength)
       at System.IO.Path.NormalizePath(String path, Boolean fullCheck)
       at System.IO.Path.GetFullPathInternal(String path)
       at System.Reflection.RuntimeModule.get_FullyQualifiedName()
  4. System.ArgumentException: Illegal characters in path.
       at System.IO.LongPathHelper.Normalize(String path, UInt32 maxPathLength, Boolean checkInvalidCharacters, Boolean expandShortPaths)
       at System.IO.Path.NewNormalizePath(String path, Int32 maxPathLength, Boolean expandShortPaths)
       at System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
       at System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength)
       at System.IO.Path.NormalizePath(String path, Boolean fullCheck)
       at System.IO.Path.GetFullPathInternal(String path)
       at System.Reflection.RuntimeModule.get_FullyQualifiedName()
  5. System.ArgumentException: Illegal characters in path.
       at System.IO.LongPathHelper.Normalize(String path, UInt32 maxPathLength, Boolean checkInvalidCharacters, Boolean expandShortPaths)
       at System.IO.Path.NewNormalizePath(String path, Int32 maxPathLength, Boolean expandShortPaths)
       at System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
       at System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength)
       at System.IO.Path.NormalizePath(String path, Boolean fullCheck)
       at System.IO.Path.GetFullPathInternal(String path)
       at System.Reflection.RuntimeModule.get_FullyQualifiedName()
  6. System.ArgumentException: Illegal characters in path.
       at System.IO.LongPathHelper.Normalize(String path, UInt32 maxPathLength, Boolean checkInvalidCharacters, Boolean expandShortPaths)
       at System.IO.Path.NewNormalizePath(String path, Int32 maxPathLength, Boolean expandShortPaths)
       at System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
       at System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength)
       at System.IO.Path.NormalizePath(String path, Boolean fullCheck)
       at System.IO.Path.GetFullPathInternal(String path)
       at System.Reflection.RuntimeModule.get_FullyQualifiedName()
  7. System.ArgumentException: Illegal characters in path.
       at System.IO.LongPathHelper.Normalize(String path, UInt32 maxPathLength, Boolean checkInvalidCharacters, Boolean expandShortPaths)
       at System.IO.Path.NewNormalizePath(String path, Int32 maxPathLength, Boolean expandShortPaths)
       at System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
       at System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength)
       at System.IO.Path.NormalizePath(String path, Boolean fullCheck)
       at System.IO.Path.GetFullPathInternal(String path)
       at System.Reflection.RuntimeModule.get_FullyQualifiedName()
  8. System.ArgumentException: Illegal characters in path.
       at System.IO.LongPathHelper.Normalize(String path, UInt32 maxPathLength, Boolean checkInvalidCharacters, Boolean expandShortPaths)
       at System.IO.Path.NewNormalizePath(String path, Int32 maxPathLength, Boolean expandShortPaths)
       at System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
       at System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength)
       at System.IO.Path.NormalizePath(String path, Boolean fullCheck)
       at System.IO.Path.GetFullPathInternal(String path)
       at System.Reflection.RuntimeModule.get_FullyQualifiedName()
  9. System.ArgumentException: Illegal characters in path.
       at System.IO.LongPathHelper.Normalize(String path, UInt32 maxPathLength, Boolean checkInvalidCharacters, Boolean expandShortPaths)
       at System.IO.Path.NewNormalizePath(String path, Int32 maxPathLength, Boolean expandShortPaths)
       at System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
       at System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength)
       at System.IO.Path.NormalizePath(String path, Boolean fullCheck)
       at System.IO.Path.GetFullPathInternal(String path)
       at System.Reflection.RuntimeModule.get_FullyQualifiedName()
  10. System.ArgumentException: Illegal characters in path.
       at System.IO.LongPathHelper.Normalize(String path, UInt32 maxPathLength, Boolean checkInvalidCharacters, Boolean expandShortPaths)
       at System.IO.Path.NewNormalizePath(String path, Int32 maxPathLength, Boolean expandShortPaths)
       at System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
       at System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength)
       at System.IO.Path.NormalizePath(String path, Boolean fullCheck)
       at System.IO.Path.GetFullPathInternal(String path)
       at System.Reflection.RuntimeModule.get_FullyQualifiedName()
  11. System.ArgumentException: Illegal characters in path.
       at System.IO.LongPathHelper.Normalize(String path, UInt32 maxPathLength, Boolean checkInvalidCharacters, Boolean expandShortPaths)
       at System.IO.Path.NewNormalizePath(String path, Int32 maxPathLength, Boolean expandShortPaths)
       at System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
       at System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength)
       at System.IO.Path.NormalizePath(String path, Boolean fullCheck)
       at System.IO.Path.GetFullPathInternal(String path)
       at System.Reflection.RuntimeModule.get_FullyQualifiedName()
  12. System.ArgumentException: Illegal characters in path.
       at System.IO.LongPathHelper.Normalize(String path, UInt32 maxPathLength, Boolean checkInvalidCharacters, Boolean expandShortPaths)
       at System.IO.Path.NewNormalizePath(String path, Int32 maxPathLength, Boolean expandShortPaths)
       at System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
       at System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength)
       at System.IO.Path.NormalizePath(String path, Boolean fullCheck)
       at System.IO.Path.GetFullPathInternal(String path)
       at System.Reflection.RuntimeModule.get_FullyQualifiedName()
  13. System.NullReferenceException: Object reference not set to an instance of an object.
       at CommunityPatch.Patches.StewardSwordsAsTributePatch.Postfix(Int32& __result, MobileParty party, StatExplainer explanation) in C:\Program Files (x86)\Steam\steamapps\common\Mount & Blade II Bannerlord\Modules\CommunityPatch\src\CommunityPatch\Patches\StewardSwordsAsTributePerkPatch.cs:line 64
       at DMD<DMD<CalculateMobilePartyMemberSizeLimit_Patch3>?47444421::CalculateMobilePartyMemberSizeLimit_Patch3>(DefaultPartySizeLimitModel this, MobileParty party, StatExplainer explanation)
       at TaleWorlds.CampaignSystem.SandBox.GameComponents.Party.DefaultPartySizeLimitModel.GetPartyMemberSizeLimit(PartyBase party, StatExplainer explanation)
       at TaleWorlds.CampaignSystem.PartyBase.get_PartySizeLimit()
       at TaleWorlds.CampaignSystem.SandBox.GameComponents.Party.DefaultPartyMoraleModel.GetPartySizeMoraleEffect(MobileParty party, ExplainedNumber& result)
       at TaleWorlds.CampaignSystem.SandBox.GameComponents.Party.DefaultPartyMoraleModel.GetEffectivePartyMorale(MobileParty mobileParty, StatExplainer explanation)
       at TaleWorlds.CampaignSystem.MobileParty.get_Morale()
       at TaleWorlds.CampaignSystem.ViewModelCollection.Map.MapInfoVM.UpdatePlayerInfo()
       at TaleWorlds.CampaignSystem.ViewModelCollection.Map.MapInfoVM.Refresh()
       at TaleWorlds.CampaignSystem.ViewModelCollection.MapVM.OnRefresh()
       at SandBox.GauntletUI.Map.GauntlerMapBarGlobalLayer.Refresh()
       at SandBox.GauntletUI.Map.GauntletMapBar.OnResume()
       at SandBox.View.Map.MapScreen.OnResume()
       at TaleWorlds.Engine.Screens.ScreenBase.HandleResume()
       at TaleWorlds.Engine.Screens.ScreenManager.PopScreen()
       at TaleWorlds.MountAndBlade.View.Screen.GameStateScreenManager.TaleWorlds.Core.IGameStateManagerListener.OnPopState(GameState gameState)
       at TaleWorlds.Core.GameStateManager.OnPopState(Int32 level)
       at TaleWorlds.Core.GameStateManager.DoGameStateJobs()
       at TaleWorlds.Core.GameStateManager.PopState(Int32 popLevel)
       at SandBox.GauntletUI.GauntletKingdomScreen.CloseKingdomScreen()
       at TaleWorlds.CampaignSystem.ViewModelCollection.KingdomManagementVM.ExecuteClose()
       at TaleWorlds.CampaignSystem.ViewModelCollection.KingdomManagementVM.OnConfirmLeaveKingdomWithOption(List`1 obj)
       at TaleWorlds.Core.ViewModelCollection.PopUpVM.ExecuteProcess()
  14. System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.NullReferenceException: Object reference not set to an instance of an object.
       at CommunityPatch.Patches.StewardSwordsAsTributePatch.Postfix(Int32& __result, MobileParty party, StatExplainer explanation) in C:\Program Files (x86)\Steam\steamapps\common\Mount & Blade II Bannerlord\Modules\CommunityPatch\src\CommunityPatch\Patches\StewardSwordsAsTributePerkPatch.cs:line 64
       at DMD<DMD<CalculateMobilePartyMemberSizeLimit_Patch3>?47444421::CalculateMobilePartyMemberSizeLimit_Patch3>(DefaultPartySizeLimitModel this, MobileParty party, StatExplainer explanation)
       at TaleWorlds.CampaignSystem.SandBox.GameComponents.Party.DefaultPartySizeLimitModel.GetPartyMemberSizeLimit(PartyBase party, StatExplainer explanation)
       at TaleWorlds.CampaignSystem.PartyBase.get_PartySizeLimit()
       at TaleWorlds.CampaignSystem.SandBox.GameComponents.Party.DefaultPartyMoraleModel.GetPartySizeMoraleEffect(MobileParty party, ExplainedNumber& result)
       at TaleWorlds.CampaignSystem.SandBox.GameComponents.Party.DefaultPartyMoraleModel.GetEffectivePartyMorale(MobileParty mobileParty, StatExplainer explanation)
       at TaleWorlds.CampaignSystem.MobileParty.get_Morale()
       at TaleWorlds.CampaignSystem.ViewModelCollection.Map.MapInfoVM.UpdatePlayerInfo()
       at TaleWorlds.CampaignSystem.ViewModelCollection.Map.MapInfoVM.Refresh()
       at TaleWorlds.CampaignSystem.ViewModelCollection.MapVM.OnRefresh()
       at SandBox.GauntletUI.Map.GauntlerMapBarGlobalLayer.Refresh()
       at SandBox.GauntletUI.Map.GauntletMapBar.OnResume()
       at SandBox.View.Map.MapScreen.OnResume()
       at TaleWorlds.Engine.Screens.ScreenBase.HandleResume()
       at TaleWorlds.Engine.Screens.ScreenManager.PopScreen()
       at TaleWorlds.MountAndBlade.View.Screen.GameStateScreenManager.TaleWorlds.Core.IGameStateManagerListener.OnPopState(GameState gameState)
       at TaleWorlds.Core.GameStateManager.OnPopState(Int32 level)
       at TaleWorlds.Core.GameStateManager.DoGameStateJobs()
       at TaleWorlds.Core.GameStateManager.PopState(Int32 popLevel)
       at SandBox.GauntletUI.GauntletKingdomScreen.CloseKingdomScreen()
       at TaleWorlds.CampaignSystem.ViewModelCollection.KingdomManagementVM.ExecuteClose()
       at TaleWorlds.CampaignSystem.ViewModelCollection.KingdomManagementVM.OnConfirmLeaveKingdomWithOption(List`1 obj)
       at TaleWorlds.Core.ViewModelCollection.PopUpVM.ExecuteProcess()
       --- End of inner exception stack trace ---
       at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
       at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
       at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
       at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
       at TaleWorlds.Library.Common.InvokeWithLog(MethodInfo methodInfo, Object obj, Object[] args)
    14.1. System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.NullReferenceException: Object reference not set to an instance of an object.
       at CommunityPatch.Patches.StewardSwordsAsTributePatch.Postfix(Int32& __result, MobileParty party, StatExplainer explanation) in C:\Program Files (x86)\Steam\steamapps\common\Mount & Blade II Bannerlord\Modules\CommunityPatch\src\CommunityPatch\Patches\StewardSwordsAsTributePerkPatch.cs:line 64
       at DMD<DMD<CalculateMobilePartyMemberSizeLimit_Patch3>?47444421::CalculateMobilePartyMemberSizeLimit_Patch3>(DefaultPartySizeLimitModel this, MobileParty party, StatExplainer explanation)
       at TaleWorlds.CampaignSystem.SandBox.GameComponents.Party.DefaultPartySizeLimitModel.GetPartyMemberSizeLimit(PartyBase party, StatExplainer explanation)
       at TaleWorlds.CampaignSystem.PartyBase.get_PartySizeLimit()
       at TaleWorlds.CampaignSystem.SandBox.GameComponents.Party.DefaultPartyMoraleModel.GetPartySizeMoraleEffect(MobileParty party, ExplainedNumber& result)
       at TaleWorlds.CampaignSystem.SandBox.GameComponents.Party.DefaultPartyMoraleModel.GetEffectivePartyMorale(MobileParty mobileParty, StatExplainer explanation)
       at TaleWorlds.CampaignSystem.MobileParty.get_Morale()
       at TaleWorlds.CampaignSystem.ViewModelCollection.Map.MapInfoVM.UpdatePlayerInfo()
       at TaleWorlds.CampaignSystem.ViewModelCollection.Map.MapInfoVM.Refresh()
       at TaleWorlds.CampaignSystem.ViewModelCollection.MapVM.OnRefresh()
       at SandBox.GauntletUI.Map.GauntlerMapBarGlobalLayer.Refresh()
       at SandBox.GauntletUI.Map.GauntletMapBar.OnResume()
       at SandBox.View.Map.MapScreen.OnResume()
       at TaleWorlds.Engine.Screens.ScreenBase.HandleResume()
       at TaleWorlds.Engine.Screens.ScreenManager.PopScreen()
       at TaleWorlds.MountAndBlade.View.Screen.GameStateScreenManager.TaleWorlds.Core.IGameStateManagerListener.OnPopState(GameState gameState)
       at TaleWorlds.Core.GameStateManager.OnPopState(Int32 level)
       at TaleWorlds.Core.GameStateManager.DoGameStateJobs()
       at TaleWorlds.Core.GameStateManager.PopState(Int32 popLevel)
       at SandBox.GauntletUI.GauntletKingdomScreen.CloseKingdomScreen()
       at TaleWorlds.CampaignSystem.ViewModelCollection.KingdomManagementVM.ExecuteClose()
       at TaleWorlds.CampaignSystem.ViewModelCollection.KingdomManagementVM.OnConfirmLeaveKingdomWithOption(List`1 obj)
       at TaleWorlds.Core.ViewModelCollection.PopUpVM.ExecuteProcess()
       --- End of inner exception stack trace ---
       at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
       at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
       at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
       at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
       at TaleWorlds.Library.Common.InvokeWithLog(MethodInfo methodInfo, Object obj, Object[] args)
  15. System.InvalidOperationException: Operation is not valid due to the current state of the object.
       at System.Reflection.MemberInfo.get_MetadataToken()
       at TaleWorlds.Library.Common.GetStackTraceRaw(Exception e, Int32 skipCount)
       at TaleWorlds.Library.Common.WalkInnerExceptionRecursive(Exception InnerException, String& StackStr)
       at TaleWorlds.Library.Common.WalkInnerExceptionRecursive(Exception InnerException, String& StackStr)
       at TaleWorlds.Library.Common.PrintDynamicInvokeDebugInfo(Exception e, MethodInfo methodInfo, Object obj, Object[] args)
       at TaleWorlds.Library.Common.InvokeWithLog(MethodInfo methodInfo, Object obj, Object[] args)
       at TaleWorlds.Library.ViewModel.ExecuteCommand(String commandName, Object[] parameters)
       at TaleWorlds.GauntletUI.Data.GauntletView.OnCommand(String command, Object[] args)
       at TaleWorlds.GauntletUI.Data.GauntletView.OnEventFired(Widget widget, String commandName, Object[] args)
       at TaleWorlds.GauntletUI.Widget.EventFired(String eventName, Object[] args)
       at TaleWorlds.GauntletUI.ButtonWidget.HandleClick()
       at TaleWorlds.GauntletUI.ButtonWidget.OnMouseReleased()
       at TaleWorlds.GauntletUI.EventManager.DispatchEvent(Widget selectedWidget, GauntletEvent gauntletEvent)
       at TaleWorlds.GauntletUI.EventManager.MouseUp()
       at TaleWorlds.GauntletUI.UIContext.UpdateInput(InputType handleInputs)
       at TaleWorlds.Engine.GauntletUI.GauntletLayer.ProcessEvents()
       at TaleWorlds.Engine.Screens.ScreenManager.Update()
       at TaleWorlds.Engine.Screens.ScreenManager.Tick(Single dt)
       at ManagedCallbacks.EngineCallbacksGenerated.ScreenManager_Tick(Single dt)

Modules Information:
  1. CharacterTrainer v1.0.6
    Character Trainer (CharacterTrainer)
  Dependencies:
    1. SandBoxCore
    2. Sandbox
  2. CommunityPatch v0.0.1
    Community Patch (CommunityPatch)
  3. CustomBattle e1.0.8 *Selected*
    CustomBattle (CustomBattle) *Official*
  Dependencies:
    1. Native
    2. SandBoxCore
  4. Native e1.0.0 *Selected*
    Native (Native) *Official*
  5. Sandbox e1.0.8 *Selected*
    Sandbox (SandBox) *Official*
  Dependencies:
    1. Native
    2. SandBoxCore
  6. SandBoxCore e1.0.8 *Selected*
    SandBox Core (SandBoxCore) *Official*
  Dependencies:
    1. Native
  7. StewardPerkFix v0.1.0
    StewardPerkFix (StewardPerkFix)
  Dependencies:
    1. Native
    2. SandBoxCore
    3. Sandbox
    4. CustomBattle
    5. StoryMode
  8. StoryMode e1.0.8 *Selected*
    StoryMode (StoryMode) *Official*
  Dependencies:
    1. Native
    2. SandBoxCore
    3. Sandbox
  9. TyniBannerlordFixes v1.4.1
    TyniBannerlordFixes (TyniBannerlordFixes)
  Dependencies:
    1. Native
    2. SandBoxCore
    3. Sandbox
    4. CustomBattle
    5. StoryMode
  10. zzBannerlordTweaks v1.1.0
    Bannerlord Tweaks (zzBannerlordTweaks)
  Dependencies:
    1. Native
    2. SandBoxCore
    3. Sandbox
    4. CustomBattle
    5. StoryMode

Loaded SubModules:
  1. TaleWorlds.MountAndBlade.View.ViewSubModule, TaleWorlds.MountAndBlade.View, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
  2. TaleWorlds.MountAndBlade.GauntletUI.GauntletUISubModule, TaleWorlds.MountAndBlade.GauntletUI, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
  3. CommunityPatch.CommunityPatchSubModule, CommunityPatch, Version=0.0.1.0, Culture=neutral, PublicKeyToken=null
  4. TaleWorlds.MountAndBlade.CustomBattle.CustomBattleSubModule, TaleWorlds.MountAndBlade.CustomBattle, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
  5. SandBox.SandBoxSubModule, SandBox, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
  6. SandBox.View.SandBoxViewSubModule, SandBox.View, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
  7. SandBox.GauntletUI.SandBoxGauntletUISubModule, SandBox.GauntletUI, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
  8. StoryMode.StoryModeSubModule, StoryMode, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
  9. StoryMode.View.StoryModeViewSubModule, StoryMode.View, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
  10. StoryMode.GauntletUI.StoryModeGauntletUISubModule, StoryMode.GauntletUI, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null

System Info:
  gpu: NVIDIA GeForce GTX 1080
  cpu: Intel(R) Core(TM) i5-6600K CPU @ 3.50GHz
  
  GPU Memory: 8079MB
  GC Allocated: 283817224B
  Engine Memory Used: 0MB
  GC Latency Mode: Client Interactive
  GC LOH Compact Mode: Default
  Operating System: Microsoft Windows 10.0.17763 
  Framework Compatibility: .NET Framework 4.8.4121.0
  CPU Info:
    1. Intel Core i5-6600K with 4 cores:
      1. MHz °C
      2. MHz °C
      3. MHz °C
      4. MHz °C

```

**Comment by Tyler-IN** [comment]
Pushed a change to master to try to fix the NRE.

**Comment by tynakuh** [comment]
Confirmed it's fixed.
